-- Add top 30 Indian stock symbols from the National Stock Exchange (NSE)
INSERT INTO stock_symbols (ticker, company_name, exchange, is_active) VALUES
    ('RELIANCE', 'Reliance Industries Limited', 'NSE', true),
    ('TCS', 'Tata Consultancy Services Limited', 'NSE', true),
    ('INFY', 'Infosys Limited', 'NSE', true),
    ('HDFCBANK', 'HDFC Bank Limited', 'NSE', true),
    ('ICICIBANK', 'ICICI Bank Limited', 'NSE', true),
    ('WIPRO', 'Wipro Limited', 'NSE', true),
    ('SBIN', 'State Bank of India', 'NSE', true),
    ('BHARTIARTL', 'Bharti Airtel Limited', 'NSE', true),
    ('ITC', 'ITC Limited', 'NSE', true),
    ('KOTAKBANK', 'Kotak Mahindra Bank Limited', 'NSE', true),
    ('LT', 'Larsen & Toubro Limited', 'NSE', true),
    ('HINDUNILVR', 'Hindustan Unilever Limited', 'NSE', true),
    ('AXISBANK', 'Axis Bank Limited', 'NSE', true),
    ('BAJFINANCE', 'Bajaj Finance Limited', 'NSE', true),
    ('MARUTI', 'Maruti Suzuki India Limited', 'NSE', true),
    ('SUNPHARMA', 'Sun Pharmaceutical Industries Limited', 'NSE', true),
    ('TATAMOTORS', 'Tata Motors Limited', 'NSE', true),
    ('TITAN', 'Titan Company Limited', 'NSE', true),
    ('ULTRACEMCO', 'UltraTech Cement Limited', 'NSE', true),
    ('ASIANPAINT', 'Asian Paints Limited', 'NSE', true),
    ('NESTLEIND', 'Nestle India Limited', 'NSE', true),
    ('HCLTECH', 'HCL Technologies Limited', 'NSE', true),
    ('ADANIENT', 'Adani Enterprises Limited', 'NSE', true),
    ('POWERGRID', 'Power Grid Corporation of India Limited', 'NSE', true),
    ('NTPC', 'NTPC Limited', 'NSE', true),
    ('ONGC', 'Oil and Natural Gas Corporation Limited', 'NSE', true),
    ('JSWSTEEL', 'JSW Steel Limited', 'NSE', true),
    ('TATASTEEL', 'Tata Steel Limited', 'NSE', true),
    ('TECHM', 'Tech Mahindra Limited', 'NSE', true),
    ('BAJAJFINSV', 'Bajaj Finserv Limited', 'NSE', true)
ON CONFLICT (ticker) DO NOTHING;
